# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='days_back',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
